# Désactive la protection pour le dev
protected-mode no

# Indique à Redis de créer un fichier socket
unixsocket /var/run/redis/redis.sock
# Donne les permissions (777 permet à votre app locale d'y écrire sans souci de droits)
unixsocketperm 777

# Laisse quand même le port classique ouvert si vous en avez besoin pour d'autres tests
port 6379
